version = 1

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_root = "github.com/Alldrich/FrameworkBenchmarks"
  dependencies_vendored = true

[[analyzers]]
name = "test-coverage"
enabled = true

[[analyzers]]
name = "rust"
enabled = true

  [analyzers.meta]
  msrv = "1.30.0"

[[analyzers]]
name = "csharp"
enabled = true

[[transformers]]
name = "rustfmt"
enabled = true

[[transformers]]
name = "dotnet-format"
enabled = true